#!/bin/bash -p

# EMBA - EMBEDDED LINUX ANALYZER
#
# SPDX-License-Identifier: GPL-3.0-only
#
# Author(s): Vikash Chaudhary (based on EMBA structure)

# Description: Scan SBOM JSON components for OpenSSL and log the version

S08_submodule_grep_openssl_sbom() {
  local lPACKAGING_SYSTEM="grep_openssl_sbom"
  local lOS_IDENTIFIED="${1:-}"

  sub_module_title "SBOM OpenSSL version scanner" "${LOG_PATH_MODULE}/${lPACKAGING_SYSTEM}.txt"

  local lSBOM_JSON_FILES=()
  local lSBOM_FILE=""
  local lAPP_NAME=""
  local lAPP_VERS=""
  local lAPP_DESC="NA"
  local lAPP_LIC="NA"
  local lAPP_MAINT="NA"
  local lAPP_ARCH="NA"
  local lCPE_IDENTIFIER="NA"
  local lPURL_IDENTIFIER="NA"
  local lPOS_RES=0

  # Check if SBOM_LOG_PATH is set and valid
  if [[ -z "${SBOM_LOG_PATH}" || ! -d "${SBOM_LOG_PATH}" ]]; then
    write_log "[-] SBOM log path not found or empty: SBOM_LOG_PATH=${SBOM_LOG_PATH}" "${LOG_PATH_MODULE}/${lPACKAGING_SYSTEM}.txt"
    return
  fi

  # Find JSON files generated by other S08 modules
  mapfile -t lSBOM_JSON_FILES < <(find "${SBOM_LOG_PATH}" -maxdepth 1 -type f -name "*.json")

  if [[ "${#lSBOM_JSON_FILES[@]}" -eq 0 ]]; then
    write_log "[-] No SBOM component JSON files found in ${SBOM_LOG_PATH}" "${LOG_PATH_MODULE}/${lPACKAGING_SYSTEM}.txt"
    return
  fi

  for lSBOM_FILE in "${lSBOM_JSON_FILES[@]}"; do
    lAPP_NAME=$(jq -r '.name // empty' "${lSBOM_FILE}")
    [[ "${lAPP_NAME,,}" != "openssl" ]] && continue

    lAPP_VERS=$(jq -r '.version // empty' "${lSBOM_FILE}")
    lAPP_DESC=$(jq -r '.description // "NA"' "${lSBOM_FILE}")
    lAPP_LIC=$(jq -r '.licenses[0]?.license?.id // "NA"' "${lSBOM_FILE}")
    lAPP_MAINT=$(jq -r '.supplier // "NA"' "${lSBOM_FILE}")
    lAPP_ARCH=$(jq -r '.group // "NA"' "${lSBOM_FILE}")

    lAPP_NAME=$(clean_package_details "${lAPP_NAME}")
    lAPP_VERS=$(clean_package_versions "${lAPP_VERS}")
    lAPP_ARCH=$(clean_package_details "${lAPP_ARCH}")

    [[ -z "${lAPP_NAME}" || -z "${lAPP_VERS}" ]] && continue

    lPURL_IDENTIFIER=$(build_purl_identifier "${lOS_IDENTIFIED}" "sbom" "${lAPP_NAME}" "${lAPP_VERS}" "${lAPP_ARCH}")
    lCPE_IDENTIFIER="cpe:${CPE_VERSION}:a:${lAPP_NAME}:${lAPP_NAME}:${lAPP_VERS}:*:*:*:*:*:*"

    local lSTRIPPED_VERSION="::${lAPP_NAME}:${lAPP_VERS:-NA}"

    # Add metadata to SBOM properties
    local lPROP_ARRAY_INIT_ARR=()
    lPROP_ARRAY_INIT_ARR+=( "source_path:${lSBOM_FILE}" )
    lPROP_ARRAY_INIT_ARR+=( "minimal_identifier:${lSTRIPPED_VERSION}" )
    lPROP_ARRAY_INIT_ARR+=( "vendor_name:${lAPP_NAME}" )
    lPROP_ARRAY_INIT_ARR+=( "product_name:${lAPP_NAME}" )
    lPROP_ARRAY_INIT_ARR+=( "confidence:high" )

    build_sbom_json_properties_arr "${lPROP_ARRAY_INIT_ARR[@]}"

    if ! build_sbom_json_hashes_arr "${lSBOM_FILE}" "${lAPP_NAME}" "${lAPP_VERS}" "${lPACKAGING_SYSTEM}"; then
      write_log "[*] Duplicate OpenSSL version found: ${lAPP_NAME} / ${lAPP_VERS}" "${S08_DUPLICATES_LOG}"
      continue
    fi

    build_sbom_json_component_arr "${lPACKAGING_SYSTEM}" "library" "${lAPP_NAME}" "${lAPP_VERS}" "${lAPP_MAINT}" "${lAPP_LIC}" "${lCPE_IDENTIFIER}" "${lPURL_IDENTIFIER}" "${lAPP_DESC}"

    write_log "[*] OpenSSL SBOM Match: ${lSBOM_FILE} - ${lAPP_NAME} - ${lAPP_VERS}" "${LOG_PATH_MODULE}/${lPACKAGING_SYSTEM}.txt"
    write_csv_log "${lPACKAGING_SYSTEM}" "${lSBOM_FILE}" "NA" "${lAPP_NAME}" "${lAPP_VERS}" "${lSTRIPPED_VERSION}" "${lAPP_LIC}" "${lAPP_MAINT}" "${lAPP_ARCH}" "${lCPE_IDENTIFIER}" "${lPURL_IDENTIFIER}" "${SBOM_COMP_BOM_REF}" "${lAPP_DESC}"

    lPOS_RES=1
  done

  write_log "[*] ${lPACKAGING_SYSTEM} submodule finished." "${LOG_PATH_MODULE}/${lPACKAGING_SYSTEM}.txt"

  if [[ "${lPOS_RES}" -eq 1 ]]; then
    print_output "[+] OpenSSL SBOM results available" "" "${LOG_PATH_MODULE}/${lPACKAGING_SYSTEM}.txt"
  else
    print_output "[*] No OpenSSL SBOM results found"
  fi
}
